sudo: false
language: python
notifications:
  email: false
python:
  - pypy
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - pypy3
before_install:
  - if [[ $TRAVIS_PYTHON_VERSION == "2.6" ]]; then pip install flake8==2.6.2; fi
  - pip install -r tests/requirements.txt
script:
  make test

